### PR TITLE
Fix sunday in working days

### PR DESCRIPTION
**Pull request by ne-ray**

### CODE REVIEW

**Comment by vojtasvoboda** [comment]
What kind of problem was there? Can we add a test for that?

**Comment by ne-ray** [comment]
[Carbon](http://carbon.nesbot.com/docs/#api-constants) use 0 for sunday, but I thinked ```date('N');``` 7 for sunday.
I think test not need.

**Comment by ne-ray** [comment]
Hi. What do you think about this pull request?

**Comment by vojtasvoboda** [comment]
Hi @Ne-Ray, sorry for the delay, I was off for the vacation. I could make a little time this weekend to finish this PR. Do you think you can fix that conflict which makes merge impossible? It should be just version.yaml file.

Thanks a lot
Vojta

**Comment by ne-ray** [comment]
@vojtasvoboda ready

**Comment by ne-ray** [comment]
?

**Comment by vojtasvoboda** [comment]
Thanks for PR a lot! I could not see the problem without unit tests, but now it is clear for me. The problem was the `+ 1` in iteration because it makes lowest index 1 and not 0 for Sunday.

I have tested it in a few cases and your fix is valid.

Update 1.1.3 is now ready at the Market for download or update.

Thanks again
Vojta

**Pull request merged**
